/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedCardsNewRouteImport } from './routes/_authenticated/cards.new'
import { Route as AuthenticatedCategoriesIdRouteImport } from './routes/_authenticated/categories.$id'
import { Route as AuthenticatedStudyIndexRouteImport } from './routes/_authenticated/study.index'
import { Route as AuthenticatedStudySessionRouteImport } from './routes/_authenticated/study.session'
import { Route as AuthenticatedCardsIdIndexRouteImport } from './routes/_authenticated/cards.$id.index'
import { Route as AuthenticatedCardsIdEditRouteImport } from './routes/_authenticated/cards.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCardsNewRoute = AuthenticatedCardsNewRouteImport.update({
  id: '/cards/new',
  path: '/cards/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesIdRoute =
  AuthenticatedCategoriesIdRouteImport.update({
    id: '/categories/$id',
    path: '/categories/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudyIndexRoute = AuthenticatedStudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudySessionRoute =
  AuthenticatedStudySessionRouteImport.update({
    id: '/study/session',
    path: '/study/session',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCardsIdIndexRoute =
  AuthenticatedCardsIdIndexRouteImport.update({
    id: '/cards/$id/',
    path: '/cards/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCardsIdEditRoute =
  AuthenticatedCardsIdEditRouteImport.update({
    id: '/cards/$id/edit',
    path: '/cards/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/cards/new': typeof AuthenticatedCardsNewRoute
  '/categories/$id': typeof AuthenticatedCategoriesIdRoute
  '/study/session': typeof AuthenticatedStudySessionRoute
  '/study/': typeof AuthenticatedStudyIndexRoute
  '/cards/$id/edit': typeof AuthenticatedCardsIdEditRoute
  '/cards/$id/': typeof AuthenticatedCardsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/cards/new': typeof AuthenticatedCardsNewRoute
  '/categories/$id': typeof AuthenticatedCategoriesIdRoute
  '/study/session': typeof AuthenticatedStudySessionRoute
  '/study': typeof AuthenticatedStudyIndexRoute
  '/cards/$id/edit': typeof AuthenticatedCardsIdEditRoute
  '/cards/$id': typeof AuthenticatedCardsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/cards/new': typeof AuthenticatedCardsNewRoute
  '/_authenticated/categories/$id': typeof AuthenticatedCategoriesIdRoute
  '/_authenticated/study/session': typeof AuthenticatedStudySessionRoute
  '/_authenticated/study/': typeof AuthenticatedStudyIndexRoute
  '/_authenticated/cards/$id/edit': typeof AuthenticatedCardsIdEditRoute
  '/_authenticated/cards/$id/': typeof AuthenticatedCardsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home'
    | '/library'
    | '/profile'
    | '/invite/$token'
    | '/cards/new'
    | '/categories/$id'
    | '/study/session'
    | '/study/'
    | '/cards/$id/edit'
    | '/cards/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/library'
    | '/profile'
    | '/invite/$token'
    | '/cards/new'
    | '/categories/$id'
    | '/study/session'
    | '/study'
    | '/cards/$id/edit'
    | '/cards/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/home'
    | '/_authenticated/library'
    | '/_authenticated/profile'
    | '/invite/$token'
    | '/_authenticated/cards/new'
    | '/_authenticated/categories/$id'
    | '/_authenticated/study/session'
    | '/_authenticated/study/'
    | '/_authenticated/cards/$id/edit'
    | '/_authenticated/cards/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cards/new': {
      id: '/_authenticated/cards/new'
      path: '/cards/new'
      fullPath: '/cards/new'
      preLoaderRoute: typeof AuthenticatedCardsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories/$id': {
      id: '/_authenticated/categories/$id'
      path: '/categories/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof AuthenticatedCategoriesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/study/': {
      id: '/_authenticated/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof AuthenticatedStudyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/study/session': {
      id: '/_authenticated/study/session'
      path: '/study/session'
      fullPath: '/study/session'
      preLoaderRoute: typeof AuthenticatedStudySessionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cards/$id/': {
      id: '/_authenticated/cards/$id/'
      path: '/cards/$id'
      fullPath: '/cards/$id/'
      preLoaderRoute: typeof AuthenticatedCardsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cards/$id/edit': {
      id: '/_authenticated/cards/$id/edit'
      path: '/cards/$id/edit'
      fullPath: '/cards/$id/edit'
      preLoaderRoute: typeof AuthenticatedCardsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedCardsNewRoute: typeof AuthenticatedCardsNewRoute
  AuthenticatedCategoriesIdRoute: typeof AuthenticatedCategoriesIdRoute
  AuthenticatedStudySessionRoute: typeof AuthenticatedStudySessionRoute
  AuthenticatedStudyIndexRoute: typeof AuthenticatedStudyIndexRoute
  AuthenticatedCardsIdEditRoute: typeof AuthenticatedCardsIdEditRoute
  AuthenticatedCardsIdIndexRoute: typeof AuthenticatedCardsIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedCardsNewRoute: AuthenticatedCardsNewRoute,
  AuthenticatedCategoriesIdRoute: AuthenticatedCategoriesIdRoute,
  AuthenticatedStudySessionRoute: AuthenticatedStudySessionRoute,
  AuthenticatedStudyIndexRoute: AuthenticatedStudyIndexRoute,
  AuthenticatedCardsIdEditRoute: AuthenticatedCardsIdEditRoute,
  AuthenticatedCardsIdIndexRoute: AuthenticatedCardsIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
